version: '3.8'
services:
  superhero-api:
    build:
      context: .
      dockerfile: SuperHero.Api/Dockerfile
    depends_on:
      - krakend
    environment:
      - 'HeroApiOptions__Host=${HeroApiOptions__Host}'
      - 'HeroApiOptions__Token=${HeroApiOptions__Token}'
      - 'Application__Host=${Application__Host}'
    ports:
      - '8003:8080'
    networks:
      - krakend-network
  krakend:
    image: devopsfaith/krakend
    ports:
      - '8080:8080'
    volumes:
      - './krakend.json:/etc/krakend/krakend.json'
    networks:
      - krakend-network
networks:
  krakend-network:
    driver: bridge